# development:
#   adapter: mysql2
#   encoding: utf8
#   database: tinker_development
#   host: localhost
#   pool: 10
#   username: dlabs
#   password: dlabs

# production:
#   adapter: mysql2
#   encoding: utf8
#   database: tinker_production
#   pool: 10
#   username: dlabs
#   password: dlabs

development:
  adapter: postgresql
  encoding: unicode
  database: tinker_development
  host: localhost
  pool: 10

test:
  adapter: postgresql
  encoding: unicode
  database: tinker_test
  host: localhost
  pool: 10

production:
  adapter: postgresql
  encoding: unicode
  database: d3c24jg5vg9ceg
  pool: 10
  username: uscwbglajgeoww
  password: ZqJtWJAnTEIW_0M1WitT-K0wDh
