development:
  adapter: postgresql
  encoding: unicode
  database: tinker_development
  host: localhost
  pool: 10

test:
  adapter: postgresql
  encoding: unicode
  database: tinker_test
  host: localhost
  pool: 10
