development:
  adapter: mysql2
  encoding: utf8
  database: tinker_development
  host: localhost
  pool: 10
  username: dlabs
  password: dlabs

production:
  adapter: mysql2
  encoding: utf8
  database: tinker_production
  pool: 10
  username: dlabs
  password: dlabs
