# development:
#   adapter: mysql2
#   encoding: utf8
#   database: tinker_development
#   host: localhost
#   pool: 10
#   username: dlabs
#   password: dlabs

production:
  adapter: postgresql
  encoding: utf8
  database: tinker_production
  host: localhost
  pool: 10

development:
  adapter: postgresql
  encoding: unicode
  database: tinker_development
  host: localhost
  pool: 10

test:
  adapter: postgresql
  encoding: unicode
  database: tinker_test
  host: localhost
  pool: 10
