# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7142debd538d0be7181a69c2edb8fdb75faf5d6b27fbd314cd21d1a5297ca7cbbb436dea0fac98141c649d8d13e18da865c817668042dfff776fe46c1911e72d

test:
  secret_key_base: e50c40b367bdc96e5306fd138cee6fb760ba282d5cc53321cdd09cfbf75e9fe9c72be61ab514dbf95c2ae3012309232c1730d80910b74bc98b7af23e70a78c6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
